### ISSUE TITLE
How to collect cast errors and validate error together?

### ISSUE THREAD

**Issue by GleisonOliveira** [bluzky/tarams#20]
I have the following validation schema (it's work properly)

```elixir
  @order_params %{
    status: [type: :string, required: true, func: &Order.valid_status/1],
    user_id: [type: Ecto.UUID, required: true, func: &User.exists/1],
    services: [
      type: :array,
      required: true,
      func: &Service.has_one/1,
      cast_func: {__MODULE__, :validate_order_services}
    ]
  }
```

But when I execute the `cast`, if i have any `cast` errors, the validation errors are not returned (I receive just the cast errors), if I don't have any cast `errors`, the validation errors are showed up.

**How can I get all the errors at same time (cast and validations errors)?** 

I need all the erros at the same time, to assign all errors fields in front app.

**Comment by bluzky** [comment]
@GleisonOliveira that would be fixed soon

**Comment by bluzky** [comment]
@GleisonOliveira  now you can get full errors report. Please update to version 1.7.0
