### ISSUE TITLE
Drop non required fields from validated map

### ISSUE THREAD

**Issue by whoiswentz** [bluzky/tarams#21]
I realize that non required fields are retuned to me as nil values

```elixir
 Tarams.cast(%{"id" => "some_id"}, %{
    id: [type: :string, required: true],
    optional: [type: :string]
  })

{:ok, %{id: "some_id", optional: nil}}
```

There some parameter that I can pass to tarams to remove the non required fields from validated map?

**Comment by bluzky** [comment]
@whoiswentz You can remove nil field with 
```elixir
Tarams.clean_nil(map)
```

Tarams set value to nil for non required field so you always sure that key exist and use `map.key` without worrying that key exists or not.
